name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Set up Swift
      uses: swift-actions/setup-swift@main
      with:
        swift-version: 6.0.0

    - uses: actions/checkout@v4

    - name: Build
      run: swift build

    - name: Run tests
      run: swift test
